site_name: DpadRecyclerView
site_description: 'A RecyclerView built for Android TV'
site_author: 'Rúben Sousa'
site_url: 'https://rubensousa.github.io/dpadrecyclerview/'
remote_branch: gh-pages
edit_uri: ""
copyright: 'Copyright &copy; 2024 Rúben Sousa'

repo_name: 'DpadRecyclerView'
repo_url: 'https://github.com/rubensousa/DpadRecyclerView'

theme:
  name: 'material'
  language: 'en'
  palette:
    scheme: default
    primary: 'black'
    accent: 'light-blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - content.code.copy

extra:
  dpadrecyclerview:
    version: '1.3.0-alpha02'
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/rubensousa/DpadRecyclerView'

markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: "3"

plugins:
  - markdownextradata: {}


nav:
  - 'Overview': index.md
  - 'Getting Started': getting_started.md
  - 'Migrating from Leanback': migrating_leanback.md
  - 'Focus and selection': selection.md
  - 'Alignment': alignment.md
  - 'Compose interoperability': compose.md
  - 'Testing': testing.md
  - 'XML attributes': xml.md
  - 'Recipes':
      - 'Layout': recipes/layout.md
      - 'Spacing': recipes/spacing.md
      - 'Alignment': recipes/alignment.md
      - 'Focus': recipes/focus.md
      - 'Scrolling': recipes/scrolling.md
  - 'Changelog': changelog.md
  - 'API': api/