[versions]
# From library
android-gradle-plugin = "8.6.0"
androidx-collection = "1.4.3"
androidx-recyclerview = "1.4.0-beta01"
androidx-poolingcontainer = "1.0.0"
androidx-appcompat = "1.7.0"
androidx-compose-ui = "1.7.0-rc01"
androidx-test-espresso = '3.6.1'
androidx-test-uiautomator = '2.3.0'
# From sample
androidx-compose-material3 = '1.2.1'
androidx-constraintlayout = "2.1.4"
androidx-fragment = "1.8.2"
androidx-interpolator = "1.0.0"
androidx-leanback = "1.0.0-alpha03"
androidx-lifecycle = "2.8.4"
androidx-navigation = "2.7.7"
androidx-paging = "3.3.2"
androidx-test-core = '1.6.1'
androidx-test-espressoJunit = '1.2.1'
androidx-test-espressoTruth = '1.6.0'
androidx-test-rules = '1.6.1'
androidx-test-runner = '1.6.2'
androidx-test-services = '1.5.0'

guava = "33.1.0-android"
timber = "5.0.1"

decorator = "2.1.0"
kotlin = "2.0.0"
kover = "0.7.6"
jacoco = "0.8.11"
test-junit = '4.13.2'
test-truth = '1.4.1'
test-mockk = '1.13.10'
carioca-report = "1.0.0-beta01"
carioca-allure = "1.0.0-beta01"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
jacoco = { id = "org.jacoco.core", version.ref = "jacoco" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
carioca-allure = { id = "com.rubensousa.carioca.report.allure", version.ref = "carioca-allure" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-collection = { module = "androidx.collection:collection", version.ref = "androidx-collection" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3-android", version.ref = "androidx-compose-material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation-android", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-customview-poolingcontainer = { module = "androidx.customview:customview-poolingcontainer", version.ref = "androidx-poolingcontainer" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "androidx-fragment" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment" }
androidx-fragment-testing-manifest = { module = "androidx.fragment:fragment-testing-manifest", version.ref = "androidx-fragment" }
androidx-interpolator = { module = "androidx.interpolator:interpolator", version.ref = "androidx-interpolator" }
androidx-leanback-grid = { module = "androidx.leanback:leanback-grid", version.ref = "androidx-leanback" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "androidx-navigation" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-test-compose-ui-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose-ui" }
androidx-test-compose-ui-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose-ui" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test-core" }
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-test-espresso" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-espresso-idling = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "androidx-test-espresso" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-espressoJunit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-services = { module = "androidx.test.services:test-services", version.ref = "androidx-test-services" }
androidx-test-truth = { module = "androidx.test.ext:truth", version.ref = "androidx-test-espressoTruth" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidx-test-uiautomator" }
carioca-report = { module = "com.rubensousa.carioca:report-android", version.ref = "carioca-report"}
decorator = { module = "com.rubensousa:decorator", version.ref = "decorator" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "test-junit" }
mockk = { module = "io.mockk:mockk", version.ref = "test-mockk" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
truth = { module = "com.google.truth:truth", version.ref = "test-truth" }
